# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FileData_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 600)
        Dialog.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.FileName = QtWidgets.QTableWidget(Dialog)
        self.FileName.setGeometry(QtCore.QRect(40, 160, 871, 411))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.FileName.setFont(font)
        self.FileName.setStyleSheet("\n"
"\n"
"\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.FileName.setObjectName("FileName")
        self.FileName.setColumnCount(1)
        self.FileName.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.FileName.setHorizontalHeaderItem(0, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 70, 351, 71))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.home = QtWidgets.QPushButton(Dialog)
        self.home.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.home.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.home.setObjectName("home")
        self.new_2 = QtWidgets.QPushButton(Dialog)
        self.new_2.setGeometry(QtCore.QRect(200, 20, 141, 31))
        self.new_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.new_2.setObjectName("new_2")
        self.profile = QtWidgets.QPushButton(Dialog)
        self.profile.setGeometry(QtCore.QRect(370, 20, 151, 31))
        self.profile.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.profile.setObjectName("profile")
        self.logout = QtWidgets.QPushButton(Dialog)
        self.logout.setGeometry(QtCore.QRect(760, 20, 151, 31))
        self.logout.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.logout.setObjectName("logout")
        self.Referes = QtWidgets.QPushButton(Dialog)
        self.Referes.setGeometry(QtCore.QRect(760, 110, 151, 31))
        self.Referes.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Referes.setObjectName("Referes")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.FileName.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "File Name"))
        self.label.setText(_translate("Dialog", "  File Data"))
        self.home.setText(_translate("Dialog", "Home"))
        self.new_2.setText(_translate("Dialog", "View History"))
        self.profile.setText(_translate("Dialog", "Profile"))
        self.logout.setText(_translate("Dialog", "LogOut"))
        self.Referes.setText(_translate("Dialog", "Referes"))



