# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Home_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 500)
        Dialog.setStyleSheet("\n"
"background-color: rgb(89, 89, 89);")
        self.token = QtWidgets.QLineEdit(Dialog)
        self.token.setGeometry(QtCore.QRect(480, 165, 250, 31))
        self.token.setObjectName("token")
        self.paste = QtWidgets.QPushButton(Dialog)
        self.paste.setGeometry(QtCore.QRect(750, 165, 93, 31))
        self.paste.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.paste.setObjectName("paste")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(480, 135, 221, 21))
        self.label.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.copy = QtWidgets.QPushButton(Dialog)
        self.copy.setGeometry(QtCore.QRect(750, 255, 93, 31))
        self.copy.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.copy.setObjectName("copy")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 351, 311))
        self.label_2.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 170);")
        self.label_2.setObjectName("label_2")
        self.home = QtWidgets.QPushButton(Dialog)
        self.home.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.home.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.home.setObjectName("home")
        self.ViewHistory = QtWidgets.QPushButton(Dialog)
        self.ViewHistory.setGeometry(QtCore.QRect(200, 20, 141, 31))
        self.ViewHistory.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ViewHistory.setObjectName("ViewHistory")
        self.profile = QtWidgets.QPushButton(Dialog)
        self.profile.setGeometry(QtCore.QRect(370, 20, 151, 31))
        self.profile.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.profile.setObjectName("profile")
        self.logout = QtWidgets.QPushButton(Dialog)
        self.logout.setGeometry(QtCore.QRect(760, 20, 151, 31))
        self.logout.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.logout.setObjectName("logout")
        self.file = QtWidgets.QLineEdit(Dialog)
        self.file.setGeometry(QtCore.QRect(480, 250, 250, 31))
        self.file.setObjectName("file")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(480, 220, 151, 21))
        self.label_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.paste.setText(_translate("Dialog", "Paste"))
        self.label.setText(_translate("Dialog", "  Enter Your Token Or File Name"))
        self.copy.setText(_translate("Dialog", "Copy"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Copy Paste <br/>AnyWhere</span></p></body></html>"))
        self.home.setText(_translate("Dialog", "Home"))
        self.ViewHistory.setText(_translate("Dialog", "View History"))
        self.profile.setText(_translate("Dialog", "Profile"))
        self.logout.setText(_translate("Dialog", "LogOut"))
        self.label_3.setText(_translate("Dialog", "Upload File"))


