# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 500)
        Dialog.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(90, 90, 90);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(670, 80, 111, 71))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 210, 100, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(550, 280, 101, 31))
        self.label_3.setObjectName("label_3")
        self.EmailId = QtWidgets.QLineEdit(Dialog)
        self.EmailId.setGeometry(QtCore.QRect(672, 210, 201, 31))
        self.EmailId.setObjectName("EmailId")
        self.Password = QtWidgets.QLineEdit(Dialog)
        self.Password.setGeometry(QtCore.QRect(670, 280, 201, 31))
        self.Password.setObjectName("Password")
        self.Login = QtWidgets.QPushButton(Dialog)
        self.Login.setGeometry(QtCore.QRect(720, 370, 150, 28))
        self.Login.setObjectName("Login")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(660, 340, 141, 16))
        self.label_4.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.signup = QtWidgets.QPushButton(Dialog)
        self.signup.setGeometry(QtCore.QRect(800, 340, 71, 21))
        self.signup.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.signup.setObjectName("signup")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 100, 351, 311))
        self.label_5.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 170);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Email Id"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.Login.setText(_translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "   Don\'t have account ?"))
        self.signup.setText(_translate("Dialog", "Signup"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Copy Paste <br/>AnyWhere</span></p></body></html>"))



