# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(931, 577)
        signup.setStyleSheet("background-color: rgb(74, 74, 74);")
        self.label = QtWidgets.QLabel(signup)
        self.label.setGeometry(QtCore.QRect(610, 60, 171, 81))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(signup)
        self.label_2.setGeometry(QtCore.QRect(540, 190, 81, 31))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.Name = QtWidgets.QLineEdit(signup)
        self.Name.setGeometry(QtCore.QRect(650, 190, 201, 31))
        self.Name.setObjectName("Name")
        self.Email = QtWidgets.QLineEdit(signup)
        self.Email.setGeometry(QtCore.QRect(650, 250, 200, 31))
        self.Email.setObjectName("Email")
        self.label_3 = QtWidgets.QLabel(signup)
        self.label_3.setGeometry(QtCore.QRect(540, 250, 80, 31))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(signup)
        self.label_4.setGeometry(QtCore.QRect(530, 310, 101, 31))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.Password = QtWidgets.QLineEdit(signup)
        self.Password.setGeometry(QtCore.QRect(650, 310, 200, 31))
        self.Password.setObjectName("Password")
        self.label_5 = QtWidgets.QLabel(signup)
        self.label_5.setGeometry(QtCore.QRect(480, 370, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.Conformpassword = QtWidgets.QLineEdit(signup)
        self.Conformpassword.setGeometry(QtCore.QRect(650, 370, 200, 31))
        self.Conformpassword.setObjectName("Conformpassword")
        self.Submit = QtWidgets.QPushButton(signup)
        self.Submit.setGeometry(QtCore.QRect(720, 440, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.Submit.setObjectName("Submit")
        self.back = QtWidgets.QPushButton(signup)
        self.back.setGeometry(QtCore.QRect(720, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back.setFont(font)
        self.back.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.back.setObjectName("back")
        self.label_6 = QtWidgets.QLabel(signup)
        self.label_6.setGeometry(QtCore.QRect(80, 110, 351, 311))
        self.label_6.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 170);")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Dialog"))
        self.label.setText(_translate("signup", " SignUp"))
        self.label_2.setText(_translate("signup", "  Name"))
        self.label_3.setText(_translate("signup", "  Email"))
        self.label_4.setText(_translate("signup", " Password"))
        self.label_5.setText(_translate("signup", "Conform Password"))
        self.Submit.setText(_translate("signup", "Submit"))
        self.back.setText(_translate("signup", "Back To Login"))
        self.label_6.setText(_translate("signup", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Copy Paste <br/>AnyWhere</span></p></body></html>"))


#
